# EDA

## Prerequisite

### Import libraries

In [1]:
import duckdb
from pathlib import Path
from src.configs import DB_SAVE_PATH
from loguru import logger

import pandas as pd

### Import database

In [2]:
try:
    con = duckdb.connect(Path(DB_SAVE_PATH), read_only=True)
    logger.success("Database connected")
except duckdb.Error as err:
    logger.error(f"Unable to connect to database at {DB_SAVE_PATH}: {err}")

2026-10-22 11:17:32.034 | SUCCESS  | __main__:<module>:3 - Database connected

## Data overview

In [23]:
print("Database version:", con.execute("""
    SELECT *
    FROM version
""").fetchone()[0])

Database version: e44f186d6f06dd8452aaf54c7921ba66c961f637

### Database schema

In [31]:
db_stats = []

db_tables = con.execute("""
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_type = 'BASE TABLE'
""").fetchall()

for (table,) in db_tables:
    row_count = con.execute(f"""
        SELECT COUNT(*) 
        FROM \"{table}\"
    """).fetchone()[0]

    col_count = con.execute(f"""
        SELECT COUNT(*) 
        FROM information_schema.columns 
        WHERE table_name = '{table}'
    """).fetchone()[0]

    db_stats.append(
        {"table_name": table, "row_count": row_count, "column_count": col_count}
    )

stats_df = pd.DataFrame(db_stats).sort_values(by="row_count", ascending=False).reset_index(drop=True)
display(stats_df)

           table_name  row_count  column_count
0        game_lineups    3179016            10
1         appearances    1894350            13
2         game_events    1274469            11
3   player_valuations     656301             6
4          club_games     177916            11
5           transfers     175165            10
6               games      88958            23
7             players      50149            26
8               clubs        796            17
9      national_teams        124            17
10          countries        124             8
11       competitions         65            11
12            version          1             1

### Review of quantitative features

In [33]:
NUMERIC_TYPES = (
    r"^(U?(TINY|SMALL|BIG|HUGE)?INT(EGER)?|FLOAT|DOUBLE|REAL|DECIMAL.*|NUMERIC.*)$"
)

summaries = []
for (table, ) in db_tables:
    df = con.execute(f"""
        SELECT '{table}' AS table_name, s.*
        FROM (SUMMARIZE {table}) s
        WHERE regexp_matches(s.column_type, '{NUMERIC_TYPES}')
          AND s.column_name NOT LIKE '%!_id' ESCAPE '!'
    """).df()
    if not df.empty:
        summaries.append(df)

quantitative_features = pd.concat(summaries, ignore_index=True)
display(
    quantitative_features[
        [
            "table_name",
            "column_name",
            "column_type",
            "min",
            "max",
            "avg",
            "std",
            "q25",
            "q50",
            "q75",
            "null_percentage",
        ]
    ].sort_values(by="null_percentage").reset_index(drop=True)
)

,table_name,column_name,column_type,min,max,avg,std,q25,q50,q75,null_percentage
0,appearances,yellow_cards,INTEGER,0,2,0.14493520204819596,0.3621893845084208,0,0,0,0.00
1,appearances,red_cards,INTEGER,0,1,0.0034777100324649615,0.05886949460327004,0,0,0,0.00
2,appearances,goals,INTEGER,0,6,0.0952500857814026,0.32951475143908937,0,0,0,0.00
3,appearances,assists,INTEGER,0,6,0.07496238815424816,0.2844562854892381,0,0,0,0.00
4,appearances,minutes_played,INTEGER,0,148,68.51902235595323,30.20032758520065,46,90,90,0.00
5,clubs,squad_size,INTEGER,0,50,26.776381909547737,8.28746086095652,25,28,31,0.00
6,clubs,national_team_players,INTEGER,0,24,3.9233668341708543,4.576989944500191,0,2,6,0.00
7,clubs,foreigners_number,INTEGER,0,36,10.552763819095478,6.6873375058937565,5,10,15,0.00
8,club_games,opponent_goals,INTEGER,0,19,1.4626171901346703,1.3977599137560466,0,1,2,0.00
9,club_games,own_goals,INTEGER,0,19,1.4626171901346703,1.3977599137560475,0,1,2,0.00
10,clubs,stadium_seats,INTEGER,0,87523,24269.773869346733,17484.44626774555,10850,20103,32227,0.00
11,games,away_club_goals,INTEGER,0,19,1.328492097394276,1.3575094748146777,0,1,2,0.00
12,countries,average_age,FLOAT,22.7,31.8,26.23387093697825,1.3210544622247788,25.449999809265137,26.200000762939453,27.050000190734863,0.00
13,countries,total_players,INTEGER,1,921,405.0403225806452,150.50621353316353,300,389,490,0.00
14,countries,total_clubs,INTEGER,6,36,14.241935483870968,4.6806485683283325,10,14,16,0.00
15,club_games,is_win,INTEGER,0,1,0.39151060050810493,0.4880895299106222,0,0,1,0.00
16,national_teams,foreigners_number,INTEGER,0,30,14.07258064516129,8.191978415456008,7,14,22,0.00
17,national_teams,squad_size,INTEGER,19,33,25.31451612903226,1.9437911807108503,24,26,26,0.00
18,national_teams,average_age,FLOAT,21.0,30.5,26.866935530016498,1.6448847444425347,26.100000381469727,26.899999618530273,28.0,0.00
19,game_lineups,team_captain,INTEGER,0,1,0.04707808957237082,0.2118059422358695,0,0,0,0.00
20,game_events,minute,INTEGER,-1,120,62.09317370606896,23.39995239875781,46,67,80,0.00
21,games,home_club_goals,INTEGER,0,15,1.5967422828750646,1.4243159958379463,1,1,2,0.00
22,player_valuations,market_value_in_eur,INTEGER,0,200000000,2290092.7440290353,6721808.734569112,200199,499880,1500651,0.00
23,national_teams,fifa_ranking,INTEGER,1,211,79.66935483870968,56.83319220460653,32,68,124,0.00
24,national_teams,total_market_value,INTEGER,350000,947000000,130891125.4,193772367.96675855,8015000,34375000,195250000,3.23
25,clubs,average_age,FLOAT,0.0,30.1,25.46464382060914,2.4483549442708816,24.45249981880188,25.61322357240787,26.7225004196167,4.77
26,national_teams,foreigners_percentage,FLOAT,3.8,100.0,58.96379329007247,28.697769959302157,34.599998474121094,59.29999923706055,88.5,6.45
27,clubs,foreigners_percentage,FLOAT,2.4,100.0,40.036413030132,20.13970530642202,23.883333065635277,39.52851268673731,54.80719310693574,7.54
28,players,height_in_cm,INTEGER,17,210,181.9974445221038,7.426225555791066,177,182,187,8.70
29,games,attendance,INTEGER,1,99354,18282.464947860022,17922.474718743368,4423,12363,26366,12.14
30,players,market_value_in_eur,INTEGER,10000,200000000,1511049.2920439222,5854556.454154651,102050,265673,721790,17.19
31,players,highest_market_value_in_eur,INTEGER,10000,200000000,3450773.4540550956,9347394.390237499,292408,758719,2501512,17.19
32,competitions,total_clubs,INTEGER,10,30,17.16,3.8564020452610848,16,18,20,23.08
33,club_games,own_position,INTEGER,1,21,9.19931268775263,5.283429128032285,5,9,13,28.53
34,club_games,opponent_position,INTEGER,1,21,9.19931268775263,5.28342912803228,5,9,13,28.53
35,games,home_club_position,INTEGER,1,21,9.109513848476746,5.272237099847557,5,9,13,28.53
36,games,away_club_position,INTEGER,1,21,9.289111527028515,5.293115698280037,5,9,14,28.53
37,transfers,transfer_fee,"DECIMAL(18,3)",0.000,222000000.000,739835.9696231048,4245002.941229216,0,0,0,35.12
38,transfers,market_value_in_eur,"DECIMAL(18,3)",10000.000,180000000.000,1753553.918041213,4714252.500439802,196892,422956,1254833,38.91
39,players,international_goals,INTEGER,0,146,1.182940690225253,4.159747368130747,0,0,1,61.40
40,players,international_caps,INTEGER,0,233,11.370737755734655,18.988176426730625,1,4,12,61.40
41,clubs,total_market_value,FLOAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00

#### Initial observations

##### NULL rates

- `total_market_value` in `clubs` has a 100% null rate, which means that the maintainer hasn't found any club's valuation up to this point → **Remove column from consideration**.
- `international_goals` in `players` has `min` of 0 but also about 61.4% of NULL values → **Needs exploring to see whether there is a difference between players with no international cap versus players with international caps but have scored zero goals versus players with no national cap data.**
- Both `market_value_in_eur` and `highest_market_value_in_eur` in `players` have the same NULL rates of ~17.19% → **Need checking whether the non-NULL entries are connected; as well as exploring the cohorts of players (academy players who still haven't had a markvet valuation, or (near-)retired players who don't need a player valuation).**
- The `*_position` columns in both `club_games` and `games` has the same NULL rate of ~28.53% → **Needs exploring further to see whether those games with NULL entries are cup games (which usually have no league position) or just low-coverage.**
- Are NULL values clustered together (by club, by competition, by country) or spread out.

##### Irregular values

- `minute` in `game_events` has min value of `-1` → **Needs exploring further to see the reason (normal minutes are usually non-negative, so -1 might be a placeholder)**.
- `own_goals` and  `opponent_goals` have near-identical general statistics → **Needs exploring further to see whether there between any difference in these two colunms or are they just copies of one another**.
- Many features have irregular minimal/maximum values:
    - Minimum of `average_age` in `clubs` is 0.
    - Minimum of `height_in_cm` in `players` is 17.
    - Minimum of `stadium_seats` in `clubs` is 0.
    - Minimum of `attendance` in `games` is 1.
    - Maximum of `minutes_played` in `appearances` is 148.

#### Data Exploration (1)

##### Question 1. Is `-1` in `minute` in `game_events` a placeholder?

Assumption: `-1` in `minute` in `game_events` is only a placeholder for a game with low-coverage (with minutes not logged)

In [11]:
nonpositive_min_events = con.execute("""
    SELECT *
    FROM game_events
    WHERE minute <= 0
""").df()

print(
    f"Number of game events with logged minute less or equal to 0: {len(nonpositive_min_events)}"
)
display(nonpositive_min_events)

print(
    f"Types of game events correlated with `minute` = -1: {list(nonpositive_min_events['type'].unique())}"
)

Number of game events with logged minute less or equal to 0: 17575

,game_event_id,date,game_id,minute,type,club_id,club_name,player_id,description,player_in_id,player_assist_id
0,587290140ebb0e436795bd4406fc6afe,2010-06-29,1027049,-1,Shootout,3581,Paraguay,2050,", Scored",<NA>,<NA>
1,6a7ec555f265921db64bf05304171894,2010-06-29,1027049,-1,Shootout,3581,Paraguay,16120,", Scored",<NA>,<NA>
2,0ed09be6d9c6643c6f05aa5a720221c6,2010-06-29,1027049,-1,Shootout,3435,Japan,27513,", Scored",<NA>,<NA>
3,b79cb0d0f6ae63bcd548ea4d64eb8640,2010-06-29,1027049,-1,Shootout,3581,Paraguay,37713,", Scored",<NA>,<NA>
4,80b2dbf5a7815aead1b85d7c414da362,2010-06-29,1027049,-1,Shootout,3435,Japan,38777,", Missed",<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...
17570,99d42bf1eed86e9140d4438b9ce0750d,2008-06-22,910151,-1,Shootout,3375,Spain,7840,", Scored",<NA>,<NA>
17571,1e9d8d9e1de7cb9772395e308a0b386e,2008-06-22,910151,-1,Shootout,3375,Spain,7980,", Scored",<NA>,<NA>
17572,e8be853ce02272d8b456b3c3d8340e0e,2008-06-22,910151,-1,Shootout,3375,Spain,8186,", Saved",<NA>,<NA>
17573,d33fd390a43bbedc563589c363c2408b,2008-06-22,910151,-1,Shootout,3375,Spain,8806,", Scored",<NA>,<NA>
17574,3a420345dcc81d6e0af99acf470afb5f,2008-06-22,910151,-1,Shootout,3375,Spain,15799,", Scored",<NA>,<NA>

Types of game events correlated with `minute` = -1: ['Shootout', 'Cards', 'Substitutions', 'Goals']

In [6]:
con.execute("""
    SELECT type,
           COUNT(*) AS n_events,
           COUNT(*) FILTER (WHERE minute = -1) AS n_neg_events,
           ROUND(100.0 * COUNT(*) FILTER (WHERE minute = -1) / COUNT(*), 4) AS pct_neg_events
    FROM game_events
    GROUP BY type
    ORDER BY n_neg_events DESC
""").df()

            type  n_events  n_neg_events  pct_neg_events
0       Shootout     13574         13574        100.0000
1          Cards    381753          3784          0.9912
2          Goals    247803           118          0.0476
3  Substitutions    631339            99          0.0157

- From the table, we can see that 100% of shootout goals has `minute=1`, which is explainable because shootouts are outside of official game time.
- For the other types of in-game events, they are few (< 1%), which might suggest a different reason for the `-1` placeholder → Might be cards issued after official time (due to on-field fighting, boycotts, or fan interruptions).

In [ ]:
con.execute("""
    WITH neg_events AS (
        SELECT game_id, COUNT(*) AS n_neg_cards
        FROM game_events ge
        WHERE ge.type = 'Cards' AND ge.minute = -1
        GROUP BY game_id
    ),
    per_game AS (
        SELECT game_id,
               COUNT(*) AS n_events,
               COUNT(*) FILTER (WHERE minute <> -1) AS n_normal
        FROM game_events
        GROUP BY game_id
    )
    SELECT COUNT(*) AS games_with_neg_cards,
           COUNT(*) FILTER (WHERE p.n_normal = 0) AS games_with_no_normal_events
    FROM neg_events n 
    JOIN per_game p 
    USING (game_id)
""").df()

   games_with_neg_cards  games_with_no_normal_events
0                  1178                            6

We can see only 6 games have zero coverage minute-by-minute on all event type compared to the 1178 games with a `minute` placeholder, thus support the theory more.

In [35]:
CATEGORICAL_TYPES = r"^(VARCHAR|BOOLEAN|ENUM.*)$"

summaries = []
for (table,) in db_tables:
    df = con.execute(f"""
        SELECT '{table}' AS table_name, s.*
        FROM (SUMMARIZE {table}) s
        WHERE regexp_matches(s.column_type, '{CATEGORICAL_TYPES}')
          AND s.column_name NOT LIKE '%!_id' ESCAPE '!'
    """).df()
    if not df.empty:
        summaries.append(df)

qualitative_features = pd.concat(summaries, ignore_index=True)
qualitative_features["unique_ratio"] = (
    qualitative_features["approx_unique"] / qualitative_features["count"]
).round(4)

display(
    qualitative_features[
        [
            "table_name",
            "column_name",
            "column_type",
            "approx_unique",
            "unique_ratio",
            "count",
            "null_percentage",
        ]
    ]
    .sort_values(by=["table_name", "approx_unique"])
    .reset_index(drop=True)
)

,table_name,column_name,column_type,approx_unique,unique_ratio,count,null_percentage
0,appearances,player_name,VARCHAR,28987,0.0153,1894350,0.00
1,club_games,hosting,VARCHAR,2,0.0000,177916,0.00
2,club_games,own_manager_name,VARCHAR,6550,0.0368,177916,0.95
3,club_games,opponent_manager_name,VARCHAR,6550,0.0368,177916,0.95
4,clubs,last_season,VARCHAR,12,0.0151,796,0.00
...,...,...,...,...,...,...,...
69,transfers,transfer_season,VARCHAR,34,0.0002,175165,0.00
70,transfers,to_club_name,VARCHAR,12593,0.0719,175165,0.00
71,transfers,from_club_name,VARCHAR,15260,0.0871,175165,0.00
72,transfers,player_name,VARCHAR,18558,0.1059,175165,0.00
73,version,commit_hash,VARCHAR,1,1.0000,1,0.00

In [38]:
TEMPORAL_TYPES = r"^(DATE|TIME.*|TIMESTAMP.*)$"

summaries = []
for (table,) in db_tables:
    df = con.execute(f"""
        SELECT '{table}' AS table_name, s.*
        FROM (SUMMARIZE {table}) s
        WHERE regexp_matches(s.column_type, '{TEMPORAL_TYPES}')
    """).df()
    if not df.empty:
        summaries.append(df)

temporal_features = pd.concat(summaries, ignore_index=True)
display(
    temporal_features[
        [
            "table_name",
            "column_name",
            "column_type",
            "min",
            "max",
            "approx_unique",
            "null_percentage",
        ]
    ].reset_index(drop=True)
)

,table_name,column_name,column_type,min,max,approx_unique,null_percentage
0,appearances,date,DATE,2012-07-03,2026-06-28,4345,0.00
1,games,date,DATE,2006-06-09,2026-07-06,4847,0.00
2,game_events,date,DATE,2006-06-09,2026-07-06,4847,0.00
3,game_lineups,date,DATE,2013-07-02,2026-07-06,4236,0.00
4,players,date_of_birth,TIMESTAMP,1968-07-31 00:00:00,2011-02-23 00:00:00,8460,0.10
5,players,contract_expiration_date,TIMESTAMP,2000-05-31 00:00:00,2035-06-30 00:00:00,228,37.03
6,player_valuations,date,DATE,2000-01-20,2026-06-12,5369,0.00
7,transfers,transfer_date,DATE,1993-07-01,2030-06-30,5316,0.00

In [6]:
con.close()